/*
Problem Title: Generating Fibonacci Sequence

Problem Description:

Write a C++ program that generates and prints the Fibonacci sequence based on user input.

Input:

The program should take one integer input, n, from the user, where n is a positive integer greater than zero.

Output:

The program should generate and print the first n numbers of the Fibonacci sequence. Each number should be printed on a separate line.

Fibonacci Sequence:

The Fibonacci sequence is a series of numbers in which each number (known as a Fibonacci number) is the sum of the two preceding ones. It starts with 0 and 1, and the subsequent numbers are generated by adding the last two numbers in the sequence.

The sequence begins as follows:

0, 1, 1, 2, 3, 5, 8, 13, ...
Program Requirements:

The program should repeatedly ask the user for input until a positive integer greater than zero (n) is provided.

Once a valid input is received, the program should generate and print the first n numbers of the Fibonacci sequence.

The program should handle invalid input gracefully. If the user enters a non-positive integer (0 or negative), dont print anything to console and continue to ask for input until a valid input is given.

Example:


Enter a positive integer (n) to generate the Fibonacci sequence:
7
0
1
1
2
3
5
8
*/
// Lab Template

#include <iostream>

using namespace std;

int main()
{
    cout << "Hello world" << endl;
    int num;
    cin >> num;
    int firstNum = 0;
    int secondNum = 1;
    int thirdNum = 0;
    for (int i = 0; i < num; i++)
    {
        if (i < 2)
        {
            cout << i << endl;
        }
        else
        {
            thirdNum = secondNum + firstNum;
            cout << thirdNum << endl;
            firstNum = secondNum;
            secondNum = thirdNum;
        }
    }
    if (num != 0)
        cout << endl;
    return 0;
}
